// 152.123.123.234
export const staticIp = '152.123.123.234';

export const defaultMerchant = {
  id: 15585,
  email: 'ram+ecommerce@bytize.in',
  name: 'Ram+ecommerce',
  username: 'ram+ecommerce@bytize.in',
  phone: {number: '9699145367', code: '91'},
  is_admin: true,
  locations: [],
  location: {
    id: 12353,
    name: 'Chennai',
    address: {
      city: 'chennai',
      region: 'tamilnadu',
      country: 'India',
      postal_code: '600119',
      address_line_1: 'Elcot Sez, Sholinganallur, Chennai, Tamil Nadu 600119',
      address_line_2: 'Elcot Sez, Sholinganallur, Chennai, Tamil Nadu 600119',
    },
    custom_attributes: {
      crn: '',
      fln: '',
      trn: '',
      crn_label: 'CIN',
      fln_label: 'FSSAI',
      trn_label: 'GSTIN',
      delivery_mode: 'instant',
      location_alias: '',
      min_order_value: '0',
      min_pickup_time: '0',
      order_seq_reset: '',
      order_seq_prefix: '',
      pickup_available: true,
      min_delivery_time: '0',
      delivery_available: true,
      order_delivery_days: '0',
      auto_location_toggle: '1',
      delivery_partner_mode: 'manual',
      max_delivery_distance: '50000',
    },
    latitude: '13.08430000',
    longitude: '80.27050000',
  },
  device: {
    id: 11372,
    name: 'Main',
    ref_code_prefix: '##0515',
    is_primary: true,
    settings: {
      refCode: {date: '2024-12-31T05:55:01.274Z', count: '0234'},
      orderCount: 2,
      lastForceSyncDate: '31',
      nextBussinessOpeningTime: 'Fri Dec 27 2024 00:00:00 GMT+0530',
    },
  },
  merchant: {
    id: 10869,
    m_code: 'M0010869',
    name: 'Ram+ecommerce',
    lead_id: 12785,
    brand_name: 'Ram+ecommerce',
    business_name: 'Ram+ecommerce',
    partner: {id: 1, name: 'POSBytz', slug: 'posbytz'},
    business_type: {id: 7, slug: 'restaurant', description: 'Restaurant'},
    sub_business_type: {
      id: 166,
      name: 'Bar & Restaurant',
      short_name: 'bar_and_restaurant',
      custom_attributes: {business_types: 'restaurant'},
    },
    timezone: 'Asia/Kolkata',
    country_code: 'IN',
    currency_code: 'INR',
    language_code: 'en',
    logo_url:
      'https://s3-ap-south-1.amazonaws.com/posbytz/merchants/c585fab6-fbc0-44fe-8ef8-65935bba4eab-letter.png',
    custom_attributes: {
      crn: '',
      trn: '',
      stages: ['store_domain_created'],
      crn_label: 'Company Registration Number',
      trn_label: 'TRN',
      state_code: 'TN',
      allow_import: 1,
      bank_details: {
        bank_code: '',
        bank_name: '',
        account_number: '',
        bank_code_label: '',
      },
      multiple_mrp: 1,
      business_hours: {closing: '', opening: ''},
      currency_symbol: '₹',
      letter_head_img: '',
      whatsapp_number: '',
    },
    business_email: 'ram+ecommerce@bytize.in',
    business_phone: {number: '9699145367', calling_code: '91'},
    business_address: {
      city: 'Chennai',
      region: 'Tamil Nadu',
      country: 'India',
      postal_code: '600119',
      address_line_1:
        '3rd Floor, Tower-C, TEK MEADOWS, OMR, Elcot Sez, Sholinganallur, Chennai, Tamil Nadu 600119',
      address_line_2:
        '3rd Floor, Tower-C, TEK MEADOWS, OMR, Elcot Sez, Sholinganallur, Chennai, Tamil Nadu 600119',
    },
    website_url: '',
    settings: {
      po: {
        default: {mrp: '1', 'buying-price': '1', 'selling-price': '1'},
        apply_tax_after_discount: '1',
      },
      sale: {
        custom_sale: '5680427',
        custom_refund: true,
        gift_card_sale: '5680427',
        sell_modifiers: true,
        supported_currencies: ['AED', 'USD', 'QAR', 'SAR', 'INR'],
      },
      report: {
        timings: {
          lunch: {to: {hour: '', minutes: ''}, from: {hour: '', minutes: ''}},
          dinner: {to: {hour: '', minutes: ''}, from: {hour: '', minutes: ''}},
          breakfast: {
            to: {hour: '', minutes: ''},
            from: {hour: '', minutes: ''},
          },
          'evening tiffin': {
            to: {hour: '', minutes: ''},
            from: {hour: '', minutes: ''},
          },
        },
      },
      barcode: {
        price: {type: 'single_quantity', end_index: '0', start_index: '0'},
        barcode: {end_index: '0', start_index: '0'},
        quantity: {end_index: '0', start_index: '0'},
      },
      general: {
        ads_url: '',
        ads_type: '',
        auto_sync: true,
        kot_template: 'delivery',
        tip_mandatory: false,
        auto_clock_out: false,
        custom_barcode: true,
        invoice_counter: '4',
        item_expiration: {hour: '', minutes: ''},
        reprint_receipt: true,
        restaurant_flow: 'table',
        round_off_total: false,
        show_item_image: false,
        tip_percentages: ['5', '10', '15', '20'],
        enable_caller_id: true,
        invoice_template: 'template_2',
        print_brand_name: false,
        price_to_quantity: false,
        is_table_mandatory: false,
        mask_customer_info: false,
        daily_report_emails: [],
        show_available_cash: true,
        sync_after_clock_in: false,
        kiosk_idle_stat_time: '30',
        multi_employee_kiosk: true,
        print_refund_reciept: true,
        shift_order_transfer: true,
        add_to_cart_on_submit: true,
        is_customer_mandatory: false,
        show_shipping_details: false,
        tax_calculation_phase: 'after_discount',
        auto_repair_sync_queue: false,
        enable_cash_management: true,
        enable_customer_pricing: false,
        include_tax_in_subtotal: false,
        enable_marketing_consent: false,
        enable_modifier_quantity: true,
        print_alternate_language: false,
        select_waiter_at_checkout: false,
        show_default_table_layout: true,
        capture_customer_signature: false,
        cogs_based_on_buying_price: false,
        enable_token_number_system: true,
        apply_discount_on_each_item: false,
        order_sequential_reset_time: 'year',
        enable_employee_gps_tracking: false,
        order_sequential_reset_month: '1',
        enable_credit_otp_verification: false,
        show_consolidate_shift_summary: true,
        enable_credit_limit_restriction: false,
        price_category_select_mandatory: false,
        print_shift_summary_on_clockout: true,
        enable_tracking_empty_containers: false,
        advance_order_reminder_alert_time: '9',
        enable_inventory_stock_restriction: false,
        multi_employee_kiosk_clockout_time: '',
        calculate_loyalty_for_discounted_sale: true,
        multi_employee_kiosk_clockout_inactive: false,
        enable_variation_name_same_as_item_name: true,
        request_payment_upon_online_order_accept: true,
      },
      invoice: {
        cin: true,
        fln: true,
        trn: true,
        city: true,
        term: true,
        region: true,
        country: true,
        date_time: true,
        postal_code: true,
        website_url: true,
        phone_number: true,
        address_line_1: true,
        address_line_2: true,
        footer_content: '',
        invoice_footer: false,
        invoice_number: true,
        items_font_size: '12',
        print_company_name: true,
        company_name_font_size: '18',
        print_customer_address: true,
        print_merchant_address: true,
        invoice_number_font_size: '12',
        invoice_heading_font_size: '18',
        tax_invoice_heading_font_size: '18',
        merchant_and_customer_details_font_size: '12',
      },
      receipt: {
        cin: true,
        fln: false,
        trn: true,
        city: true,
        label: {
          discount: 'Discount',
          tip_label: 'Tips',
          customer_trn_label: '',
        },
        region: true,
        address: true,
        charges: true,
        country: true,
        preview: true,
        cin_font: '12',
        datetime: true,
        fln_font: '12',
        item_hsn: true,
        item_mrp: true,
        otp_font: '12',
        quantity: true,
        trn_font: '12',
        item_name: true,
        print_uom: true,
        sub_total: true,
        tax_total: true,
        cart_items: true,
        item_price: true,
        item_total: true,
        logo_width: '150',
        total_font: '18',
        bill_number: true,
        logo_height: '150',
        postal_code: true,
        tax_message: false,
        tip_message: true,
        total_items: true,
        website_url: true,
        address_font: '12',
        charges_font: '12',
        company_name: true,
        item_barcode: true,
        phone_number: true,
        address_line1: true,
        address_line2: true,
        customer_code: true,
        customer_name: true,
        datetime_font: '12',
        discount_font: '12',
        balance_amount: true,
        customer_phone: true,
        footer_message: true,
        header_message: true,
        invoice_number: true,
        payment_method: true,
        receipt_header: true,
        sub_total_font: '12',
        tax_total_font: '12',
        total_quantity: false,
        cart_items_font: '12',
        print_signature: true,
        bill_number_font: '12',
        customer_address: true,
        employee_details: true,
        posbytz_branding: true,
        tax_message_text: 'E & O.E, #Inc Tax',
        website_url_font: '12',
        company_name_font: '12',
        item_tax_split_up: true,
        phone_number_font: '12',
        credit_amount_font: '12',
        customer_code_font: '12',
        customer_name_font: '12',
        customer_trn_label: 'VAT',
        print_cash_summary: true,
        print_item_summary: true,
        customer_phone_font: '12',
        footer_message_font: '12',
        footer_message_text: '',
        header_message_font: '12',
        header_message_text: '',
        invoice_number_font: '12',
        payment_method_font: '12',
        price_category_font: '12',
        print_brand_summary: true,
        print_shift_summary: true,
        receipt_header_text: 'Tax Invoice',
        online_order_id_font: '12',
        print_charge_summary: true,
        print_credit_summary: true,
        print_refund_summary: true,
        customer_address_font: '12',
        discount_against_item: '',
        employee_details_font: '12',
        print_cash_in_summary: true,
        print_channel_summary: true,
        print_payment_summary: true,
        item_discount_split_up: true,
        print_cash_out_summary: true,
        print_employee_summary: true,
        qr_footer_message_text: '',
        cart_item_modifier_font: '12',
        outstanding_amount_font: '12',
        print_items_alpha_order: true,
        print_qr_footer_message: true,
        amount_saved_on_mrp_font: '12',
        price_category_label_font: '12',
        current_outstanding_amount: true,
        discount_against_item_font: '12',
        print_denomination_summary: true,
        previous_outstanding_amount: true,
        print_advance_order_summary: true,
        empty_container_details_font: '12',
        print_price_category_summary: true,
        duplicate_receipt_header_text: 'Duplicate Invoice',
        print_foreign_currency_summary: true,
        print_refunded_payment_methods: true,
        print_category_wise_item_summary: true,
        print_offline_online_item_summary_separately: true,
      },
      quotation: {
        discount_apply_on: 'order',
        invoice_number_prefix: 'INV',
        add_variation_desc_in_quotation: false,
      },
      kot_receipt: {
        date: true,
        table: true,
        number: true,
        date_font: '12',
        items_font: '12',
        table_font: '12',
        title_font: '12',
        number_font: '12',
        waiter_name: true,
        customer_name: true,
        invoice_number: true,
        price_category: true,
        restaurant_name: true,
        waiter_name_font: '12',
        customer_name_font: '12',
        invoice_number_font: '12',
        price_category_font: '12',
        online_order_id_font: '12',
        restaurant_name_font: '12',
      },
      denominations: [
        {type: 'note', amount: 2000},
        {type: 'note', amount: 500},
        {type: 'note', amount: 200},
        {type: 'note', amount: 100},
        {type: 'note', amount: 50},
        {type: 'note', amount: 20},
        {type: 'note', amount: 10},
        {type: 'note', amount: 5},
        {type: 'coin', amount: 10},
        {type: 'coin', amount: 5},
        {type: 'coin', amount: 2},
        {type: 'coin', amount: 1},
      ],
      shift_summary: {
        tip_font: '12',
        print_tip: true,
        refund_font: '12',
        print_refund: true,
        discounts_font: '12',
        net_sales_font: '12',
        net_total_font: '12',
        round_off_font: '12',
        print_discounts: true,
        print_net_sales: true,
        print_net_total: true,
        print_round_off: true,
        gross_sales_font: '12',
        cash_summary_font: '12',
        print_gross_sales: true,
        category_name_font: '12',
        tax_collected_font: '12',
        title_heading_font: '12',
        print_tax_collected: true,
        employee_summary_font: '12',
        item_summary_detail_font: '12',
        shift_summary_detail_font: '12',
        credit_summary_detail_font: '12',
        refund_summary_detail_font: '12',
        channel_summary_detail_font: '12',
        charges_summary_detail_font: '12',
        deduct_refunded_payment_methods: false,
        price_brand_summary_detail_font: '12',
        denominations_summary_detail_font: '12',
        payment_method_summary_detail_font: '12',
        price_category_summary_detail_font: '12',
        include_refunded_tax_in_refunds_summary: false,
        refund_payment_method_summary_detail_font: '12',
      },
      'admin-settings': {
        low_stock_alert_time: '',
        batch_expiry_alert_in_days: '',
        enable_loyalty_point_expiry: false,
        edit_applyon_in_price_category: false,
        display_remaining_qty_for_child_variation: true,
        quotation_sale_inventory_stock_restriction: false,
      },
    },
    features: {},
    subscription: {
      id: 12785,
      tax: 0,
      name: 'Premium',
      slug: 'premium',
      total: 0,
      period: 'year',
      end_date: '2025-11-08 18:29:59',
      products: {
        items: {
          id: 20,
          qty: 1,
          name: 'Number of products',
          slug: 'items',
          limit: -1,
          period: 'year',
          identifier: 'items',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        loyalty: {
          id: 8,
          qty: 0,
          name: 'Loyalty Management (Per Location)',
          slug: 'loyalty',
          limit: null,
          period: 'year',
          identifier: 'loyalty_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        discount: {
          id: 25,
          qty: 0,
          name: 'Discount coupons',
          slug: 'discount',
          limit: null,
          period: 'year',
          identifier: 'discount',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        employee: {
          id: 5,
          qty: 20,
          name: 'Employee Accounts',
          slug: 'employee',
          limit: 10,
          period: 'year',
          identifier: 'user',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        location: {
          id: 4,
          qty: 12,
          name: 'Locations',
          slug: 'location',
          limit: 2,
          period: 'year',
          identifier: 'location',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        referral: {
          id: 11,
          qty: 0,
          name: 'Customer Referral Management (Per Location)',
          slug: 'referral',
          limit: null,
          period: 'year',
          identifier: 'referral_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        bandwidth: {
          id: 21,
          qty: 1,
          name: 'Network Bandwidth',
          slug: 'bandwidth',
          limit: -1,
          period: 'year',
          identifier: 'bandwidth',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        restaurant: {
          id: 7,
          qty: 0,
          name: 'Table & KOT Management (Per Location)',
          slug: 'restaurant',
          limit: null,
          period: 'year',
          identifier: 'restaurant_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        waiter_app: {
          id: 51,
          qty: 0,
          name: 'Waiter App (Per Location)',
          slug: 'waiter_app',
          limit: null,
          period: 'year',
          identifier: 'waiter_app_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        advanced_crm: {
          id: 70,
          qty: 1,
          name: 'Advanced CRM (Per Location)',
          slug: 'advanced_crm',
          limit: null,
          period: 'year',
          identifier: 'advanced_crm',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 1,
        },
        chat_support: {
          id: 37,
          qty: 0,
          name: 'Chat',
          slug: 'chat_support',
          limit: null,
          period: 'year',
          identifier: 'chat_support',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        delivery_app: {
          id: 28,
          qty: 0,
          name: 'Delivery App',
          slug: 'delivery_app',
          limit: null,
          period: 'year',
          identifier: 'delivery_app_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        integrations: {
          id: 27,
          qty: 0,
          name: 'Integrations',
          slug: 'integrations',
          limit: null,
          period: 'year',
          identifier: 'integrations',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        online_store: {
          id: 17,
          qty: 0,
          name: 'Online Store (Web & Website)',
          slug: 'online_store',
          limit: null,
          period: 'year',
          identifier: 'online_store',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        email_support: {
          id: 35,
          qty: 0,
          name: 'Email',
          slug: 'email_support',
          limit: null,
          period: 'year',
          identifier: 'email_support',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        phone_support: {
          id: 36,
          qty: 0,
          name: 'Phone',
          slug: 'phone_support',
          limit: null,
          period: 'year',
          identifier: 'phone_support',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        advanced_report: {
          id: 30,
          qty: 0,
          name: 'Professional Pro Reports (Per Location)',
          slug: 'advanced_report',
          limit: null,
          period: 'year',
          identifier: 'advanced_report_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        kitchen_display: {
          id: 52,
          qty: 0,
          name: 'Kitchen Display Screen (KDS) (Per Location)',
          slug: 'kitchen_display',
          limit: null,
          period: 'year',
          identifier: 'kitchen_display_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        report_download: {
          id: 29,
          qty: 0,
          name: 'Export Reports',
          slug: 'report_download',
          limit: null,
          period: 'year',
          identifier: 'report_download',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        foreign_currency: {
          id: 65,
          qty: 1,
          name: 'Foreign Currency (Per Location)',
          slug: 'foreign_currency',
          limit: null,
          period: 'year',
          identifier: 'foreign_currency_v2',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 1,
        },
        own_brand_domain: {
          id: 34,
          qty: 0,
          name: 'Custom Domain (Per Location)',
          slug: 'own_brand_domain',
          limit: null,
          period: 'year',
          identifier: 'own_brand_domain_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        priority_support: {
          id: 38,
          qty: 0,
          name: 'Priority support',
          slug: 'priority_support',
          limit: null,
          period: 'year',
          identifier: 'priority_support',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        advanced_discount: {
          id: 26,
          qty: 0,
          name: 'Advanced Discounts (Per Location)',
          slug: 'advanced_discount',
          limit: null,
          period: 'year',
          identifier: 'advanced_discount_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        own_brand_ios_app: {
          id: 32,
          qty: 0,
          name: 'Branded iOS shopping app',
          slug: 'own_brand_ios_app',
          limit: null,
          period: 'year',
          identifier: 'own_brand_ios_app_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        store_integration: {
          id: 60,
          qty: 10,
          name: 'Online Store Integrations (Per Location)',
          slug: 'store_integration',
          limit: null,
          period: 'year',
          identifier: 'store_integration_v2',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        others_integration: {
          id: 67,
          qty: 10,
          name: 'Others Integrations (Per Location)',
          slug: 'others_integration',
          limit: null,
          period: 'year',
          identifier: 'others_integration_v2',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        pos_device_license: {
          id: 23,
          qty: 12,
          name: 'Point of Sale',
          slug: 'pos_device_license',
          limit: 2,
          period: 'year',
          identifier: 'device_license',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        purchase_inventory: {
          id: 24,
          qty: 0,
          name: 'Purchase and Inventory Management (Per Location)',
          slug: 'purchase_inventory',
          limit: null,
          period: 'year',
          identifier: 'purchase_inventory_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        campaign_management: {
          id: 73,
          qty: 1,
          name: 'Campaign Management (Per Location)',
          slug: 'campaign_management',
          limit: null,
          period: 'year',
          identifier: 'campaign_management_v2',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 1,
        },
        delivery_integration: {
          id: 61,
          qty: 10,
          name: 'Delivery Integrations (Per Location)',
          slug: 'delivery_integration',
          limit: null,
          period: 'year',
          identifier: 'delivery_integration_v2',
          description: '',
          product_type: 'add-on',
          subscribed_qty: 10,
        },
        own_brand_android_app: {
          id: 31,
          qty: 0,
          name: 'Branded Android shopping app',
          slug: 'own_brand_android_app',
          limit: null,
          period: 'year',
          identifier: 'own_brand_android_app_v2',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        store_theme_customization: {
          id: 33,
          qty: 0,
          name: 'Theme Customization',
          slug: 'store_theme_customization',
          limit: null,
          period: 'year',
          identifier: 'store_theme_customization',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
        online_store_owner_android_ios: {
          id: 19,
          qty: 0,
          name: 'Android and iOS store management app (Owner app)',
          slug: 'online_store_owner_android_ios',
          limit: null,
          period: 'year',
          identifier: 'online_store_owner_android_ios',
          description: '',
          product_type: 'base',
          subscribed_qty: 0,
        },
      },
      sub_total: 0,
      start_date: '2024-11-06 18:30:00',
      description: '',
      currency_code: 'inr',
      original_end_date: '2025-11-06 18:29:59',
      limitations: null,
      status: {
        id: 116,
        name: 'Active',
        short_name: 'active',
        custom_attributes: null,
      },
      invoice_status: 'paid',
      dunning_period: '2',
    },
    platforms: [
      'pos_store',
      'posbytz',
      'zest_wing',
      'dunzo',
      'ecommerce',
      'advanced_inventory',
      'campaign_management',
    ],
    business_category: {
      id: 70,
      name: 'General',
      short_name: 'general',
      custom_attributes: null,
    },
    is_cloud_kitchen: false,
    parent_merchant: {},
    child_merchants: [],
    domains: {
      custom_domain: {domain: '', active: false},
      default_domain: {
        domain: 'ramecommerce.posbytz.com',
        active: true,
        validation_token: null,
      },
    },
    credit: 45,
    transaction_charges: {sms: 1},
    store: {
      enabled: true,
      settings: {
        general: {
          logo_img_url: '',
          default_user_location: {name: '', lat: '', lng: ''},
          catalog: {
            out_of_stock: true,
            food_type_filter: false,
            tax_split_up: true,
            track_online_inventory: false,
            item_grouping: false,
            show_sub_category: false,
          },
          order_cancellation: {
            enabled: true,
            customer_cancellation: {
              enabled: true,
              max_cancellation_time: '20',
              cancellable_status: [
                {name: 'payment authorized', id: 'payment_authorized'},
                {name: 'cod authorized', id: 'cod_authorized'},
                {name: 'confirmed', id: 'confirmed'},
                {name: 'dispatched', id: 'dispatched'},
              ],
            },
            delivery_partner_cancellation: {
              enabled: true,
              max_cancellation_time: '20',
              cancellable_status: [
                {name: 'assigned', id: 'assigned'},
                {name: 'at store', id: 'at_store'},
                {name: 'pickedup', id: 'pickedup'},
              ],
            },
          },
          social_media_pages: {
            facebook_page_url: '',
            instagram_page_url: '',
            twitter_page_url: '',
          },
          round_off_total: false,
          timezone: 'Asia/Kolkata',
          country_code: 'IN',
          language_code: 'en',
          currency_code: 'INR',
          currency_symbol: '₹',
          tax_calculation_phase: 'after_discount',
          initiate_delivery_service: 'confirmed',
          registration_verification_source: 'phone',
          support: {support_phone: '', whatsapp_phone: '', email: ''},
          quantity_increment_value: '',
          order_weight_limit: '',
          show_alert_banner: false,
          alert_banner_template: '',
          sms_otp_template: '',
          order_preparation: {total_time: '', grace_time: ''},
          store_meta: [],
        },
      },
    },
  },
  policies: {
    crm: ['create', 'read', 'update'],
    item: ['create', 'read', 'update', 'delete'],
    bills: ['create', 'read', 'update', 'delete'],
    report: [
      'sales-summary',
      'payment-methods',
      'item-sales',
      'category-sales',
      'sales-trend',
      'employee-sales',
      'location-sales',
      'customer-sales',
      'customer-items',
      'customer-no-sales',
      'taxes',
      'purchase-order-refund',
      'purchase-order-tax',
      'sales-aggregate',
      'refunds',
      'supplier-credit',
      'customers',
      'combo-sales',
      'charges',
      'export',
      'franchise',
      'franchise-sale',
      'granular-item-sales',
      'tips',
      'tables',
      'waiter-sales',
      'kot-items',
      'price-category-sales',
      'multi-currency-orders',
      'brand-sales',
      'advance-order-items',
      'item-variation-tags',
      'discounts',
    ],
    account: ['edit-profile', 'change-password', 'settings', 'delete', 'totp'],
    credits: ['create', 'read'],
    loyalty: ['create', 'read', 'update', 'delete', 'activation'],
    'api-keys': ['create', 'read', 'update', 'delete'],
    customer: [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'export',
      'login',
    ],
    employee: ['create', 'read', 'update', 'activation'],
    estimate: ['create', 'read', 'update', 'delete', 'invoice'],
    reportv2: ['sales', 'order-delivery'],
    template: ['create', 'read', 'update', 'delete'],
    appPolicy: {
      cart: [
        'apply discount',
        'apply custom discount',
        'apply charges',
        'apply custom charge',
        'apply_gift_card',
        'remove_charge',
      ],
      sell: [
        'view',
        'add item',
        'edit item',
        'custom sale',
        'custom_refund',
        'gift_card_sale',
        'check_stock_availability',
      ],
      sales: [
        'refund',
        'print receipt',
        'manage other orders',
        'exchange',
        'edit',
      ],
      tables: [
        'view',
        'complete order',
        'cancel order',
        'reduce quantity',
        'print receipt',
        'resend kot',
        'edit',
      ],
      reports: ['view', 'print'],
      settings: ['view', 'edit', 'item_on_off', 'custom_refund'],
      customers: ['view', 'pay credit', 'view containers'],
      drive_thru: [
        'view',
        'complete order',
        'cancel order',
        'reduce quantity',
        'print receipt',
        'resend kot',
        'edit',
      ],
      employee_shift: ['transfer_pending_order'],
      cash_management: [
        'view',
        'cash in',
        'cash out',
        'view_opening_cash_amount',
        'view_closing_cash_amount',
        'view_cash_in',
        'view_cash_out',
        'view_sales',
        'view_refunds',
        'view_cash_drawer_shifts',
      ],
      online_platform: ['view', 'edit'],
      delivery_payment: ['edit'],
      payment_gateway_credentials: ['view', 'edit'],
    },
    inventory: [
      'create',
      'read',
      'update',
      'delete',
      'inventory-audit',
      'print-barcode',
      'adjust-stock',
      'export',
      'view-selling-price',
      'view-buying-price',
      'view-mrp',
      'reset',
      'view-stock',
    ],
    marketing: ['read'],
    'store-cms': ['create', 'read', 'update'],
    accounting: ['create', 'read', 'update', 'delete'],
    'item-taxes': ['create', 'read', 'update', 'delete', 'activation'],
    'bulk-orders': ['create', 'read', 'update', 'delete', 'sale-convert'],
    'export-file': ['create', 'read'],
    'import-file': ['data-import'],
    'item-brands': ['create', 'read', 'update', 'delete', 'export'],
    'item-charges': ['create', 'read', 'update', 'delete'],
    transactions: ['read', 'refund', 'export', 'status-update', 'pay-credit'],
    auto_campaign: ['create', 'read', 'update', 'delete'],
    communication: ['read'],
    crm_dashboard: ['read'],
    'inventory-grn': ['create', 'read', 'update', 'delete'],
    'inventory-log': ['read'],
    'online-orders': ['read', 'cancel', 'refund'],
    'store-banners': ['create', 'read', 'update'],
    'account-delete': ['delete-transactions', 'delete-inventories'],
    'customer-items': ['read'],
    'employee-roles': ['create', 'read', 'update'],
    'item-discounts': ['create', 'read', 'update', 'delete', 'activation'],
    'item-gift-card': [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'export',
    ],
    'printer-labels': [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'print',
    ],
    'store-settings': ['read', 'update'],
    'account-devices': ['create', 'read', 'update', 'activation'],
    'customer-groups': ['create', 'read', 'update', 'delete'],
    'item-categories': ['create', 'read', 'update', 'delete'],
    'opening-balance': ['create', 'read', 'update', 'delete'],
    advanced_loyalty: ['create', 'read', 'update', 'delete'],
    'customer-credits': ['create', 'read', 'export'],
    'inventory-indent': [
      'create',
      'read',
      'update',
      'delete',
      'unrestricted-access',
      'approve',
      'transfer',
      'edit',
      'complete',
    ],
    'inventory-report': [
      'purchase-order-tax-summary',
      'purchase-orders-summary',
      'stock',
      'cost-of-goods',
      'cost-of-goods-summary',
      'transfer-order-summary',
      'vendor-return-summary',
      'waste-management-summary',
      'price-change',
      'stock-valuation',
      'export',
      'item-sales',
      'category-sales',
      'transfer-order-items',
      'waste-management-items',
      'vendor-return',
    ],
    'account-locations': ['create', 'read', 'update', 'activation'],
    'employee-activity': ['read', 'close-shift'],
    'inventory-credits': ['create', 'read', 'export'],
    'inventory-history': ['read', 'export'],
    'inventory-vendors': ['create', 'read', 'activation', 'update', 'export'],
    'restaurant-floors': ['create', 'read', 'update', 'delete'],
    'restaurant-tables': ['create', 'read', 'update', 'delete'],
    'cash-drawer-events': ['read', 'export'],
    'cash-drawer-shifts': ['read'],
    campaign_management: ['create', 'read', 'update', 'delete'],
    feedback_management: ['create', 'read', 'update', 'delete'],
    'inventory-preparation': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'item-price-categories': ['create', 'read', 'update', 'activation'],
    'notification-templates': ['create', 'read', 'update', 'activation'],
    'account-pg-integrations': ['create', 'read', 'update', 'authorize'],
    'inventory-vendor-return': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'inventory-purchase-order': [
      'create',
      'read',
      'approve',
      'reject',
      'receive',
      'close',
      'return',
      'pay-due',
      'refund',
      'export',
      'delete',
      'update-price',
    ],
    'inventory-transfer-order': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
      'edit',
    ],
    'inventory-inventory-count': [
      'create',
      'read',
      'approve',
      'export',
      'delete',
      'update',
    ],
    'merchant-attribute-values': ['create', 'read', 'update', 'delete'],
    'accounting-account-mapping': ['create', 'read', 'update', 'delete'],
    'accounting-manual-journals': ['create', 'read', 'update', 'delete'],
    'integration-store-settings': ['read', 'update'],
    'inventory-waste-management': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'account-others-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'accounting-chart-of-accounts': ['create', 'read', 'update', 'delete'],
    'account-delivery-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-einvoice-integrations': ['create', 'read', 'update', 'authorize'],
    'accounting-accounting-exports': ['read'],
    'accounting-accounting-imports': ['data-import', 'read'],
    'accounting-accounting-reports': ['create', 'read', 'update', 'delete'],
    'account-marketing-integrations': ['create', 'read', 'update', 'authorize'],
    'accounting-accounting-expenses': ['create', 'read', 'update', 'delete'],
    'account-accounting-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-hr_payroll-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
    'accounting-accounting-dashboard': ['read'],
    'account-merchant-payment-methods': [
      'create',
      'read',
      'update',
      'activation',
    ],
    'account-online_store-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-communication-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
  },
};

export const defaultEmployee = {
  id: 15644,
  merchant_id: 10869,
  name: 'Employee 1',
  type: '{"id":67,"name":"Staff","short_name":"staff"}',
  username: 'Employee 1',
  email: 'ram+emp1@bytize.in',
  phone: '',
  calling_code: '91',
  passkey: 1111,
  policy: {
    crm: ['create', 'read', 'update'],
    item: ['create', 'read', 'update', 'delete'],
    bills: ['create', 'read', 'update', 'delete'],
    report: [
      'sales-summary',
      'payment-methods',
      'item-sales',
      'category-sales',
      'sales-trend',
      'employee-sales',
      'location-sales',
      'customer-sales',
      'customer-items',
      'customer-no-sales',
      'taxes',
      'purchase-order-refund',
      'purchase-order-tax',
      'sales-aggregate',
      'refunds',
      'supplier-credit',
      'customers',
      'combo-sales',
      'charges',
      'export',
      'franchise',
      'franchise-sale',
      'granular-item-sales',
      'tips',
      'tables',
      'waiter-sales',
      'kot-items',
      'price-category-sales',
      'multi-currency-orders',
      'brand-sales',
      'advance-order-items',
      'item-variation-tags',
      'discounts',
    ],
    account: ['edit-profile', 'change-password', 'settings', 'delete', 'totp'],
    credits: ['create', 'read'],
    loyalty: ['create', 'read', 'update', 'delete', 'activation'],
    'api-keys': ['create', 'read', 'update', 'delete'],
    customer: [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'export',
      'login',
    ],
    employee: ['create', 'read', 'update', 'activation'],
    estimate: ['create', 'read', 'update', 'delete', 'invoice'],
    reportv2: ['sales', 'order-delivery'],
    template: ['create', 'read', 'update', 'delete'],
    appPolicy: {
      cart: [
        'apply discount',
        'apply custom discount',
        'apply charges',
        'apply custom charge',
        'apply_gift_card',
        'remove_charge',
      ],
      sell: [
        'view',
        'add item',
        'edit item',
        'custom sale',
        'custom_refund',
        'gift_card_sale',
        'check_stock_availability',
      ],
      sales: [
        'refund',
        'print receipt',
        'manage other orders',
        'exchange',
        'edit',
      ],
      tables: [
        'view',
        'complete order',
        'cancel order',
        'reduce quantity',
        'print receipt',
        'resend kot',
        'edit',
      ],
      reports: ['view', 'print'],
      settings: ['view', 'edit', 'item_on_off', 'custom_refund'],
      customers: ['view', 'pay credit', 'view containers'],
      drive_thru: [
        'view',
        'complete order',
        'cancel order',
        'reduce quantity',
        'print receipt',
        'resend kot',
        'edit',
      ],
      employee_shift: ['transfer_pending_order'],
      cash_management: [
        'view',
        'cash in',
        'cash out',
        'view_opening_cash_amount',
        'view_closing_cash_amount',
        'view_cash_in',
        'view_cash_out',
        'view_sales',
        'view_refunds',
        'view_cash_drawer_shifts',
      ],
      online_platform: ['view', 'edit'],
      delivery_payment: ['edit'],
      payment_gateway_credentials: ['view', 'edit'],
    },
    inventory: [
      'create',
      'read',
      'update',
      'delete',
      'inventory-audit',
      'print-barcode',
      'adjust-stock',
      'export',
      'view-selling-price',
      'view-buying-price',
      'view-mrp',
      'reset',
      'view-stock',
    ],
    marketing: ['read'],
    'store-cms': ['create', 'read', 'update'],
    accounting: ['create', 'read', 'update', 'delete'],
    'item-taxes': ['create', 'read', 'update', 'delete', 'activation'],
    'bulk-orders': ['create', 'read', 'update', 'delete', 'sale-convert'],
    'export-file': ['create', 'read'],
    'import-file': ['data-import'],
    'item-brands': ['create', 'read', 'update', 'delete', 'export'],
    'item-charges': ['create', 'read', 'update', 'delete'],
    transactions: ['read', 'refund', 'export', 'status-update', 'pay-credit'],
    auto_campaign: ['create', 'read', 'update', 'delete'],
    communication: ['read'],
    crm_dashboard: ['read'],
    'inventory-grn': ['create', 'read', 'update', 'delete'],
    'inventory-log': ['read'],
    'online-orders': ['read', 'cancel', 'refund'],
    'store-banners': ['create', 'read', 'update'],
    'account-delete': ['delete-transactions', 'delete-inventories'],
    'customer-items': ['read'],
    'employee-roles': ['create', 'read', 'update'],
    'item-discounts': ['create', 'read', 'update', 'delete', 'activation'],
    'item-gift-card': [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'export',
    ],
    'printer-labels': [
      'create',
      'read',
      'update',
      'delete',
      'activation',
      'print',
    ],
    'store-settings': ['read', 'update'],
    'account-devices': ['create', 'read', 'update', 'activation'],
    'customer-groups': ['create', 'read', 'update', 'delete'],
    'item-categories': ['create', 'read', 'update', 'delete'],
    'opening-balance': ['create', 'read', 'update', 'delete'],
    advanced_loyalty: ['create', 'read', 'update', 'delete'],
    'customer-credits': ['create', 'read', 'export'],
    'inventory-indent': [
      'create',
      'read',
      'update',
      'delete',
      'unrestricted-access',
      'approve',
      'transfer',
      'edit',
      'complete',
    ],
    'inventory-report': [
      'purchase-order-tax-summary',
      'purchase-orders-summary',
      'stock',
      'cost-of-goods',
      'cost-of-goods-summary',
      'transfer-order-summary',
      'vendor-return-summary',
      'waste-management-summary',
      'price-change',
      'stock-valuation',
      'export',
      'item-sales',
      'category-sales',
      'transfer-order-items',
      'waste-management-items',
      'vendor-return',
    ],
    'account-locations': ['create', 'read', 'update', 'activation'],
    'employee-activity': ['read', 'close-shift'],
    'inventory-credits': ['create', 'read', 'export'],
    'inventory-history': ['read', 'export'],
    'inventory-vendors': ['create', 'read', 'activation', 'update', 'export'],
    'restaurant-floors': ['create', 'read', 'update', 'delete'],
    'restaurant-tables': ['create', 'read', 'update', 'delete'],
    'cash-drawer-events': ['read', 'export'],
    'cash-drawer-shifts': ['read'],
    campaign_management: ['create', 'read', 'update', 'delete'],
    feedback_management: ['create', 'read', 'update', 'delete'],
    'inventory-preparation': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'item-price-categories': ['create', 'read', 'update', 'activation'],
    'notification-templates': ['create', 'read', 'update', 'activation'],
    'account-pg-integrations': ['create', 'read', 'update', 'authorize'],
    'inventory-vendor-return': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'inventory-purchase-order': [
      'create',
      'read',
      'approve',
      'reject',
      'receive',
      'close',
      'return',
      'pay-due',
      'refund',
      'export',
      'delete',
      'update-price',
    ],
    'inventory-transfer-order': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
      'edit',
    ],
    'inventory-inventory-count': [
      'create',
      'read',
      'approve',
      'export',
      'delete',
      'update',
    ],
    'merchant-attribute-values': ['create', 'read', 'update', 'delete'],
    'accounting-account-mapping': ['create', 'read', 'update', 'delete'],
    'accounting-manual-journals': ['create', 'read', 'update', 'delete'],
    'integration-store-settings': ['read', 'update'],
    'inventory-waste-management': [
      'create',
      'read',
      'update',
      'delete',
      'approve',
      'complete',
    ],
    'account-others-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'accounting-chart-of-accounts': ['create', 'read', 'update', 'delete'],
    'account-delivery-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-einvoice-integrations': ['create', 'read', 'update', 'authorize'],
    'accounting-accounting-exports': ['read'],
    'accounting-accounting-imports': ['data-import', 'read'],
    'accounting-accounting-reports': ['create', 'read', 'update', 'delete'],
    'account-marketing-integrations': ['create', 'read', 'update', 'authorize'],
    'accounting-accounting-expenses': ['create', 'read', 'update', 'delete'],
    'account-accounting-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-hr_payroll-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
    'accounting-accounting-dashboard': ['read'],
    'account-merchant-payment-methods': [
      'create',
      'read',
      'update',
      'activation',
    ],
    'account-online_store-integrations': [
      'create',
      'read',
      'update',
      'authorize',
      'create',
      'read',
      'update',
      'authorize',
    ],
    'account-communication-integrations': [
      'create',
      'read',
      'update',
      'authorize',
    ],
  },
  locations: [],
  custom_attributes: {},
  is_admin: false,
  is_active: true,
  updated_at: '2025-01-22T06:29:33.724Z',
};

export const defaultFloors = {
  list: [
    {
      id: 1513,
      merchant_id: 10869,
      location_id: 12353,
      name: 'first floor 1',
      custom_attributes: {},
      layout: {},
      updated_at: '2025-01-22T06:29:56.635Z',
    },
  ],
  total: 1,
  offset: 0,
  loading: false,
};

export const defaultTables = {
  list: [
    {
      id: 11557,
      floor: {
        id: 1513,
        merchant_id: 10869,
        location_id: 12353,
        name: 'first floor 1',
        custom_attributes: {},
        layout: {},
        updated_at: '2025-01-22T06:29:56.635Z',
      },
      name: 'Table 1',
      seats_count: 8,
      orders: 0,
      price_category: null,
      custom_attributes: {},
      layout_attributes: {},
      is_occupied: false,
      status: 'free',
      updated_at: '2025-01-22T06:29:56.642Z',
    },
    {
      id: 11558,
      floor: {
        id: 1513,
        merchant_id: 10869,
        location_id: 12353,
        name: 'first floor 1',
        custom_attributes: {},
        layout: {},
        updated_at: '2025-01-22T06:29:56.635Z',
      },
      name: 'Table 2',
      seats_count: 8,
      orders: 0,
      price_category: null,
      custom_attributes: {},
      layout_attributes: {},
      is_occupied: false,
      status: 'free',
      updated_at: '2025-01-22T06:29:56.644Z',
    },
  ],
  total: 2,
  offset: 0,
  loading: false,
};

export const defaultVariations = {
  list: [
    {
      id: 5680704,
      merchant_id: 10869,
      item: {
        id: 5157827,
        merchant_id: 10869,
        name: 'Crispy chicken Tray',
        alternate_name: '',
        description:
          'Most popular. Lightly battered pieces of chicken stir fried with vegetables in our zesty sweet chilli sauce. Served with steamed jasmine rice',
        image_url: '',
        category: {
          id: 87790,
          merchant_id: 10869,
          name: 'Catering Trays',
          no_of_category: 0,
          parent: null,
          devices: [],
          position: 0,
          is_active: true,
          updated_at: '2025-01-22T06:29:38.472Z',
        },
        variation: [],
        custom_attributes: {},
        position: 0,
        brand: null,
        is_active: true,
        updated_at: '2025-01-22T06:29:45.745Z',
      },
      item_category_id: 87790,
      item_category_name: 'Catering Trays',
      inventory: {
        id: 6458296,
        merchant_id: 10869,
        location_id: 12353,
        kot_device: null,
        pricing_type: 'multi',
        buying_price: 120,
        selling_price: 72.99,
        original_price: 72.99,
        mrp: 145.12,
        quantity_available: 99987,
        taxes: [
          {
            id: 6925,
            merchant_id: 10869,
            name: 'VAT 13.5%',
            type: 'inclusive',
            rate: 13.5,
            is_active: true,
            updated_at: '2025-01-22T06:29:39.648Z',
          },
        ],
        batches: [
          {
            id: 535,
            barcode: null,
            buying_price: 120,
            selling_price: 72.99,
            mrp: 145.12,
            expiry_date: null,
          },
          {
            id: 535,
            barcode: null,
            buying_price: 120,
            selling_price: 72.99,
            mrp: 145.12,
            expiry_date: null,
          },
        ],
        price_categories: [],
        track_inventory: true,
        is_online_available: true,
        online_track_inventory: false,
        is_active: false,
        updated_at: '2025-01-22T06:29:45.745Z',
      },
      attributes: [],
      taxes: [
        {
          id: 6925,
          merchant_id: 10869,
          name: 'VAT 13.5%',
          type: 'inclusive',
          rate: 13.5,
          is_active: true,
          updated_at: '2025-01-22T06:29:39.648Z',
        },
      ],
      name: 'Crispy chicken Tray',
      alternate_name: '',
      description:
        'Most popular. Lightly battered pieces of chicken stir fried with vegetables in our zesty sweet chilli sauce. Served with steamed jasmine rice',
      image_url: '',
      sku: 'CzzT01',
      hsn: '',
      discounts: [],
      barcode: '',
      alternate_code: '',
      type: 'sale',
      food_type: 'nveg',
      favourite: false,
      unit_measure_type: {
        id: 242556,
        master_id: 147,
        name: 'Count',
        label: 'Count',
        short_name: 'count',
        custom_attributes: null,
      },
      combo: null,
      modifiers: [],
      custom_attributes: {
        max_price: null,
        min_price: null,
        shelf_life: null,
        comfort_factor: null,
        normal_lead_time: null,
        urgent_lead_time: null,
        alternate_language: '',
        alternate_language_description: null,
      },
      is_active: true,
      is_available: true,
      updated_at: '2025-01-22T06:29:45.745Z',
      discounted_quantity: 0,
    },
  ],
  total: 533,
  offset: 0,
  loading: false,
};
